name: Build

on:  
  push: 
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: metrik

jobs:
  buildjob:
    name: 'Test build job'
    runs-on: ubuntu-latest

    steps:
      - name: Setup timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"

      - uses: actions/checkout@v2
      - run: |
          pwd
          ls

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: maerskao.azurecr.io
          username: ${{ secrets.MAERSKAO_DOCKER_USERNAME }}
          password: ${{ secrets.MAERSKAO_DOCKER_PASSWORD }}
        run: |
          docker build -t maerskao.azurecr.io/dora-metrik:v1 ../ci/Dockerfile

        # - name: docker build and push
        #   run: |
        #     docker build -t maerskao.azurecr.io/dora-metrik:v1 ../ci/Dockerfile

# - name: Azure Container Registry Build
#   uses: Azure/acr-build@v1
#   with:
#     # Service Principal with Contributor role on the ACR
#     service_principal: 
#     # Service Principal password
#     service_principal_password: 
#     # Azure Container Registry tenant
#     tenant: 
#     # The name of the ACR, minus the .azurecr.io
#     registry: 
#     # Repository to use
#     repository: 
#     # Github access token for private repositories
#     git_access_token: 
#     # Docker image name
#     image: # optional
#     # Docker image tag, default to the commit SHA
#     tag: # optional
#     # Branch to build from, defaults to master
#     branch: # optional
#     # The folder in the Github repo that holds the source
#     folder: 
#     # The location of the Dockerfile; defaults to ./Dockerfile
#     dockerfile: # optional
#     # JSON specifying key=value pairs as as Docker build arguments
#     build_args: # optional